[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.build]
cmds = ["echo 'Building backend...'"]

[start]
cmd = "cd backend && python -m uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1"
