[providers]
python = "3.9"

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Building backend...'"]

[start]
cmd = "python -m uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1"

